apiVersion: apps/v1
kind: Deployment
metadata:
  name: rinha-frontend-deployment
spec:
  selector:
    matchLabels:
      app: rinha-frontend
  template:
    metadata:
      labels:
        app: rinha-frontend
    spec:
      containers:
      - name: rinha-frontend
        image: braganathan38/rinhafrontend-softplan:1.0
        ports:
        - containerPort: 3000
